-- ResearchPlay Supabase setup. Idempotent: safe to run again in the SQL Editor.

-- Uploaded PDFs
create table if not exists papers (
  id bigint generated by default as identity primary key,
  title text not null,
  file_name text not null,
  file_url text not null,
  file_size integer,
  uploaded_at timestamptz default now(),
  user_id uuid references auth.users(id) on delete set null
);
alter table papers enable row level security;

drop policy if exists "Anyone can read papers" on papers;
drop policy if exists "Anyone can insert papers" on papers;
drop policy if exists "Users can update their own papers" on papers;
drop policy if exists "Users can delete their own papers" on papers;
create policy "Anyone can read papers" on papers for select using (true);
create policy "Anyone can insert papers" on papers for insert with check (true);
create policy "Users can update their own papers" on papers for update using (auth.uid() = user_id);
create policy "Users can delete their own papers" on papers for delete using (auth.uid() = user_id);

-- Four-layer content authored in the studio, one row per uploaded paper.
-- content has the same shape as a paper object in src/data/papers.js (minus id).
create table if not exists paper_layers (
  paper_id bigint primary key references papers(id) on delete cascade,
  content jsonb not null default '{}'::jsonb,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table paper_layers enable row level security;

-- The studio is open to anyone for now; tighten to auth.role() = 'authenticated' once login is real.
drop policy if exists "Anyone can read paper_layers" on paper_layers;
drop policy if exists "Anyone can insert paper_layers" on paper_layers;
drop policy if exists "Anyone can update paper_layers" on paper_layers;
create policy "Anyone can read paper_layers" on paper_layers for select using (true);
create policy "Anyone can insert paper_layers" on paper_layers for insert with check (true);
create policy "Anyone can update paper_layers" on paper_layers for update using (true) with check (true);

-- Public storage bucket for the PDFs
insert into storage.buckets (id, name, public)
values ('papers', 'papers', true)
on conflict (id) do update set public = true;

drop policy if exists "Public read papers" on storage.objects;
drop policy if exists "Public upload papers" on storage.objects;
create policy "Public read papers" on storage.objects for select to public using (bucket_id = 'papers');
create policy "Public upload papers" on storage.objects for insert to public with check (bucket_id = 'papers');
